### ISSUE TITLE
Update imgui

### ISSUE THREAD

**Issue by VelocityRa** [JoshuaBrookover/bigg#13]
The current imgui version used is `1.60`, which is about a year old, the newest release as of this post is `1.69` which came out about a month ago.

**Edit:** Or I suppose you'd be limited to `1.63` which is what bgfx has right now. Which makes me wonder, why do you even have imgui as a submodule as well? bgfx already does.

**Comment by JoshuaBrookover** [comment]
To answer your question: bgfx does not use imgui, only the bgfx examples use imgui. Because we include our own examples, we can also provide our own version of imgui. When I made this repo, it was the other way around, bgfx used an old version and we had a newer version. 😄 

Upgrading imgui version should be easy enough. I'll look into it.

**Comment by VelocityRa** [comment]
That clears things up, thanks!
